sudo: required

language: ruby
rvm:
  - 2.2
  - jruby
  - truffleruby
  - 2.0.0-p247

services:
  - docker

before_install:
  - docker build -t ocobas/docker-react-sample -f Dockerfile.dev .

scripts:
  - docker run ocobas/docker-react-sample npm run test -- --coverage