sudo: required

services:
  - docker

before_install:
  - gem update --system
  - gem install bundler
  - docker build -t ocobas/docker-react-sample -f Dockerfile.dev .

scripts:
  - docker run ocobas/docker-react-sample npm run test -- --coverage