sudo: required

language: ruby
install:
  - gem uninstall bundler
  - gem install bundler --version '1.7.4'
script: "rake"

services:
  - docker

before_install:
  - docker build -t ocobas/docker-react-sample -f Dockerfile.dev .
  - 

scripts:
  - docker run ocobas/docker-react-sample npm run test -- --coverage